/* ==========================================================================
   PCC (Personal Control Center) - World Clocks Presets & Timezone Catalog
   ========================================================================== */

import { CityPreset, WorldClockItem } from './types';

/**
 * Default initial clocks presented to the user
 */
export const DEFAULT_CLOCKS: WorldClockItem[] = [
  {
    id: 'clock-ist',
    cityName: 'New Delhi / Mumbai',
    country: 'India',
    timezone: 'Asia/Kolkata',
    abbreviation: 'IST',
    flag: '🇮🇳',
    pinned: true,
  },
  {
    id: 'clock-utc',
    cityName: 'UTC / Universal',
    country: 'Global',
    timezone: 'UTC',
    abbreviation: 'UTC',
    flag: '🌐',
    pinned: true,
  },
  {
    id: 'clock-est',
    cityName: 'New York',
    country: 'United States',
    timezone: 'America/New_York',
    abbreviation: 'EST',
    flag: '🇺🇸',
    pinned: false,
  },
  {
    id: 'clock-pst',
    cityName: 'San Francisco',
    country: 'United States',
    timezone: 'America/Los_Angeles',
    abbreviation: 'PST',
    flag: '🇺🇸',
    pinned: false,
  },
  {
    id: 'clock-jst',
    cityName: 'Tokyo',
    country: 'Japan',
    timezone: 'Asia/Tokyo',
    abbreviation: 'JST',
    flag: '🇯🇵',
    pinned: false,
  },
  {
    id: 'clock-gmt',
    cityName: 'London',
    country: 'United Kingdom',
    timezone: 'Europe/London',
    abbreviation: 'GMT',
    flag: '🇬🇧',
    pinned: false,
  },
  {
    id: 'clock-aest',
    cityName: 'Sydney',
    country: 'Australia',
    timezone: 'Australia/Sydney',
    abbreviation: 'AEST',
    flag: '🇦🇺',
    pinned: false,
  },
  {
    id: 'clock-cet',
    cityName: 'Paris / Berlin',
    country: 'France / Germany',
    timezone: 'Europe/Paris',
    abbreviation: 'CET',
    flag: '🇪🇺',
    pinned: false,
  },
];

/**
 * Extensive global city presets catalog
 */
export const CITY_PRESETS: CityPreset[] = [
  // UTC
  {
    cityName: 'Coordinated Universal Time',
    country: 'Global Reference',
    timezone: 'UTC',
    abbreviation: 'UTC',
    region: 'UTC',
    flag: '🌐',
    popular: true,
  },

  // Asia
  {
    cityName: 'New Delhi',
    country: 'India',
    timezone: 'Asia/Kolkata',
    abbreviation: 'IST',
    region: 'Asia',
    flag: '🇮🇳',
    popular: true,
  },
  {
    cityName: 'Mumbai',
    country: 'India',
    timezone: 'Asia/Kolkata',
    abbreviation: 'IST',
    region: 'Asia',
    flag: '🇮🇳',
    popular: true,
  },
  {
    cityName: 'Bengaluru',
    country: 'India',
    timezone: 'Asia/Kolkata',
    abbreviation: 'IST',
    region: 'Asia',
    flag: '🇮🇳',
    popular: true,
  },
  {
    cityName: 'Tokyo',
    country: 'Japan',
    timezone: 'Asia/Tokyo',
    abbreviation: 'JST',
    region: 'Asia',
    flag: '🇯🇵',
    popular: true,
  },
  {
    cityName: 'Singapore',
    country: 'Singapore',
    timezone: 'Asia/Singapore',
    abbreviation: 'SGT',
    region: 'Asia',
    flag: '🇸🇬',
    popular: true,
  },
  {
    cityName: 'Hong Kong',
    country: 'Hong Kong SAR',
    timezone: 'Asia/Hong_Kong',
    abbreviation: 'HKT',
    region: 'Asia',
    flag: '🇭🇰',
    popular: true,
  },
  {
    cityName: 'Seoul',
    country: 'South Korea',
    timezone: 'Asia/Seoul',
    abbreviation: 'KST',
    region: 'Asia',
    flag: '🇰🇷',
    popular: true,
  },
  {
    cityName: 'Shanghai',
    country: 'China',
    timezone: 'Asia/Shanghai',
    abbreviation: 'CST',
    region: 'Asia',
    flag: '🇨🇳',
    popular: true,
  },
  {
    cityName: 'Beijing',
    country: 'China',
    timezone: 'Asia/Shanghai',
    abbreviation: 'CST',
    region: 'Asia',
    flag: '🇨🇳',
    popular: false,
  },
  {
    cityName: 'Bangkok',
    country: 'Thailand',
    timezone: 'Asia/Bangkok',
    abbreviation: 'ICT',
    region: 'Asia',
    flag: '🇹🇭',
    popular: false,
  },
  {
    cityName: 'Taipei',
    country: 'Taiwan',
    timezone: 'Asia/Taipei',
    abbreviation: 'CST',
    region: 'Asia',
    flag: '🇹🇼',
    popular: false,
  },
  {
    cityName: 'Jakarta',
    country: 'Indonesia',
    timezone: 'Asia/Jakarta',
    abbreviation: 'WIB',
    region: 'Asia',
    flag: '🇮🇩',
    popular: false,
  },
  {
    cityName: 'Kuala Lumpur',
    country: 'Malaysia',
    timezone: 'Asia/Kuala_Lumpur',
    abbreviation: 'MYT',
    region: 'Asia',
    flag: '🇲🇾',
    popular: false,
  },
  {
    cityName: 'Manila',
    country: 'Philippines',
    timezone: 'Asia/Manila',
    abbreviation: 'PHT',
    region: 'Asia',
    flag: '🇵🇭',
    popular: false,
  },

  // Americas
  {
    cityName: 'New York',
    country: 'United States',
    timezone: 'America/New_York',
    abbreviation: 'EST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: true,
  },
  {
    cityName: 'San Francisco',
    country: 'United States',
    timezone: 'America/Los_Angeles',
    abbreviation: 'PST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: true,
  },
  {
    cityName: 'Los Angeles',
    country: 'United States',
    timezone: 'America/Los_Angeles',
    abbreviation: 'PST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: true,
  },
  {
    cityName: 'Chicago',
    country: 'United States',
    timezone: 'America/Chicago',
    abbreviation: 'CST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: true,
  },
  {
    cityName: 'Toronto',
    country: 'Canada',
    timezone: 'America/Toronto',
    abbreviation: 'EST',
    region: 'Americas',
    flag: '🇨🇦',
    popular: true,
  },
  {
    cityName: 'Vancouver',
    country: 'Canada',
    timezone: 'America/Vancouver',
    abbreviation: 'PST',
    region: 'Americas',
    flag: '🇨🇦',
    popular: false,
  },
  {
    cityName: 'Seattle',
    country: 'United States',
    timezone: 'America/Los_Angeles',
    abbreviation: 'PST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: false,
  },
  {
    cityName: 'Austin',
    country: 'United States',
    timezone: 'America/Chicago',
    abbreviation: 'CST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: false,
  },
  {
    cityName: 'Denver',
    country: 'United States',
    timezone: 'America/Denver',
    abbreviation: 'MST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: false,
  },
  {
    cityName: 'Miami',
    country: 'United States',
    timezone: 'America/New_York',
    abbreviation: 'EST',
    region: 'Americas',
    flag: '🇺🇸',
    popular: false,
  },
  {
    cityName: 'Mexico City',
    country: 'Mexico',
    timezone: 'America/Mexico_City',
    abbreviation: 'CST',
    region: 'Americas',
    flag: '🇲🇽',
    popular: true,
  },
  {
    cityName: 'São Paulo',
    country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    abbreviation: 'BRT',
    region: 'Americas',
    flag: '🇧🇷',
    popular: true,
  },
  {
    cityName: 'Buenos Aires',
    country: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    abbreviation: 'ART',
    region: 'Americas',
    flag: '🇦🇷',
    popular: false,
  },
  {
    cityName: 'Bogota',
    country: 'Colombia',
    timezone: 'America/Bogota',
    abbreviation: 'COT',
    region: 'Americas',
    flag: '🇨🇴',
    popular: false,
  },
  {
    cityName: 'Santiago',
    country: 'Chile',
    timezone: 'America/Santiago',
    abbreviation: 'CLT',
    region: 'Americas',
    flag: '🇨🇱',
    popular: false,
  },

  // Europe
  {
    cityName: 'London',
    country: 'United Kingdom',
    timezone: 'Europe/London',
    abbreviation: 'GMT',
    region: 'Europe',
    flag: '🇬🇧',
    popular: true,
  },
  {
    cityName: 'Paris',
    country: 'France',
    timezone: 'Europe/Paris',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇫🇷',
    popular: true,
  },
  {
    cityName: 'Berlin',
    country: 'Germany',
    timezone: 'Europe/Berlin',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇩🇪',
    popular: true,
  },
  {
    cityName: 'Zurich',
    country: 'Switzerland',
    timezone: 'Europe/Zurich',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇨🇭',
    popular: true,
  },
  {
    cityName: 'Amsterdam',
    country: 'Netherlands',
    timezone: 'Europe/Amsterdam',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇳🇱',
    popular: true,
  },
  {
    cityName: 'Rome',
    country: 'Italy',
    timezone: 'Europe/Rome',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇮🇹',
    popular: false,
  },
  {
    cityName: 'Madrid',
    country: 'Spain',
    timezone: 'Europe/Madrid',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇪🇸',
    popular: false,
  },
  {
    cityName: 'Dublin',
    country: 'Ireland',
    timezone: 'Europe/Dublin',
    abbreviation: 'IST',
    region: 'Europe',
    flag: '🇮🇪',
    popular: false,
  },
  {
    cityName: 'Stockholm',
    country: 'Sweden',
    timezone: 'Europe/Stockholm',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇸🇪',
    popular: false,
  },
  {
    cityName: 'Vienna',
    country: 'Austria',
    timezone: 'Europe/Vienna',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇦🇹',
    popular: false,
  },
  {
    cityName: 'Warsaw',
    country: 'Poland',
    timezone: 'Europe/Warsaw',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇵🇱',
    popular: false,
  },
  {
    cityName: 'Athens',
    country: 'Greece',
    timezone: 'Europe/Athens',
    abbreviation: 'EET',
    region: 'Europe',
    flag: '🇬🇷',
    popular: false,
  },
  {
    cityName: 'Lisbon',
    country: 'Portugal',
    timezone: 'Europe/Lisbon',
    abbreviation: 'WET',
    region: 'Europe',
    flag: '🇵🇹',
    popular: false,
  },
  {
    cityName: 'Helsinki',
    country: 'Finland',
    timezone: 'Europe/Helsinki',
    abbreviation: 'EET',
    region: 'Europe',
    flag: '🇫🇮',
    popular: false,
  },
  {
    cityName: 'Prague',
    country: 'Czech Republic',
    timezone: 'Europe/Prague',
    abbreviation: 'CET',
    region: 'Europe',
    flag: '🇨🇿',
    popular: false,
  },

  // Pacific
  {
    cityName: 'Sydney',
    country: 'Australia',
    timezone: 'Australia/Sydney',
    abbreviation: 'AEST',
    region: 'Pacific',
    flag: '🇦🇺',
    popular: true,
  },
  {
    cityName: 'Melbourne',
    country: 'Australia',
    timezone: 'Australia/Melbourne',
    abbreviation: 'AEST',
    region: 'Pacific',
    flag: '🇦🇺',
    popular: true,
  },
  {
    cityName: 'Brisbane',
    country: 'Australia',
    timezone: 'Australia/Brisbane',
    abbreviation: 'AEST',
    region: 'Pacific',
    flag: '🇦🇺',
    popular: false,
  },
  {
    cityName: 'Perth',
    country: 'Australia',
    timezone: 'Australia/Perth',
    abbreviation: 'AWST',
    region: 'Pacific',
    flag: '🇦🇺',
    popular: false,
  },
  {
    cityName: 'Auckland',
    country: 'New Zealand',
    timezone: 'Pacific/Auckland',
    abbreviation: 'NZST',
    region: 'Pacific',
    flag: '🇳🇿',
    popular: true,
  },
  {
    cityName: 'Honolulu',
    country: 'United States',
    timezone: 'Pacific/Honolulu',
    abbreviation: 'HST',
    region: 'Pacific',
    flag: '🇺🇸',
    popular: false,
  },
  {
    cityName: 'Fiji',
    country: 'Fiji',
    timezone: 'Pacific/Fiji',
    abbreviation: 'FJT',
    region: 'Pacific',
    flag: '🇫🇯',
    popular: false,
  },

  // Middle East
  {
    cityName: 'Dubai',
    country: 'United Arab Emirates',
    timezone: 'Asia/Dubai',
    abbreviation: 'GST',
    region: 'Middle East',
    flag: '🇦🇪',
    popular: true,
  },
  {
    cityName: 'Abu Dhabi',
    country: 'United Arab Emirates',
    timezone: 'Asia/Dubai',
    abbreviation: 'GST',
    region: 'Middle East',
    flag: '🇦🇪',
    popular: false,
  },
  {
    cityName: 'Riyadh',
    country: 'Saudi Arabia',
    timezone: 'Asia/Riyadh',
    abbreviation: 'AST',
    region: 'Middle East',
    flag: '🇸🇦',
    popular: true,
  },
  {
    cityName: 'Doha',
    country: 'Qatar',
    timezone: 'Asia/Qatar',
    abbreviation: 'AST',
    region: 'Middle East',
    flag: '🇶🇦',
    popular: false,
  },
  {
    cityName: 'Tel Aviv',
    country: 'Israel',
    timezone: 'Asia/Jerusalem',
    abbreviation: 'IST',
    region: 'Middle East',
    flag: '🇮🇱',
    popular: false,
  },
  {
    cityName: 'Istanbul',
    country: 'Turkey',
    timezone: 'Europe/Istanbul',
    abbreviation: 'TRT',
    region: 'Middle East',
    flag: '🇹🇷',
    popular: true,
  },

  // Africa
  {
    cityName: 'Cairo',
    country: 'Egypt',
    timezone: 'Africa/Cairo',
    abbreviation: 'EET',
    region: 'Africa',
    flag: '🇪🇬',
    popular: true,
  },
  {
    cityName: 'Johannesburg',
    country: 'South Africa',
    timezone: 'Africa/Johannesburg',
    abbreviation: 'SAST',
    region: 'Africa',
    flag: '🇿🇦',
    popular: true,
  },
  {
    cityName: 'Cape Town',
    country: 'South Africa',
    timezone: 'Africa/Johannesburg',
    abbreviation: 'SAST',
    region: 'Africa',
    flag: '🇿🇦',
    popular: false,
  },
  {
    cityName: 'Nairobi',
    country: 'Kenya',
    timezone: 'Africa/Nairobi',
    abbreviation: 'EAT',
    region: 'Africa',
    flag: '🇰🇪',
    popular: true,
  },
  {
    cityName: 'Lagos',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    abbreviation: 'WAT',
    region: 'Africa',
    flag: '🇳🇬',
    popular: true,
  },
  {
    cityName: 'Casablanca',
    country: 'Morocco',
    timezone: 'Africa/Casablanca',
    abbreviation: 'WET',
    region: 'Africa',
    flag: '🇲🇦',
    popular: false,
  },
];
