"""Pydantic schemas registry."""

from app.schemas.alarm import (
    AlarmBase,
    AlarmCreate,
    AlarmListResponse,
    AlarmResponse,
    AlarmToggleRequest,
    AlarmUpdate,
)
from app.schemas.auth import (
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    UserResponse,
    UserUpdateRequest,
)
from app.schemas.base import ErrorDetail, ErrorResponse, PaginationMeta, SuccessResponse
from app.schemas.calendar_event import (
    CalendarEventBase,
    CalendarEventCreate,
    CalendarEventListResponse,
    CalendarEventResponse,
    CalendarEventUpdate,
)
from app.schemas.idea import (
    IdeaBase,
    IdeaCreate,
    IdeaListResponse,
    IdeaPromoteRequest,
    IdeaResponse,
    IdeaUpdate,
)
from app.schemas.integration import (
    IntegrationConnectRequest,
    IntegrationListResponse,
    IntegrationResponse,
    IntegrationStatusResponse,
)
from app.schemas.note import (
    NoteBase,
    NoteCreate,
    NoteListResponse,
    NoteResponse,
    NoteUpdate,
)
from app.schemas.notification import (
    NotificationBase,
    NotificationCreate,
    NotificationListResponse,
    NotificationResponse,
)
from app.schemas.project import (
    BoardCardCreate,
    BoardCardMove,
    BoardCardResponse,
    BoardColumnCreate,
    BoardColumnResponse,
    BoardCreate,
    BoardResponse,
    ProjectBase,
    ProjectCreate,
    ProjectListResponse,
    ProjectMemberCreate,
    ProjectMemberResponse,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.reminder import (
    ReminderBase,
    ReminderCreate,
    ReminderListResponse,
    ReminderResponse,
    ReminderSnoozeRequest,
    ReminderUpdate,
)
from app.schemas.task import (
    TaskCreate,
    TaskListResponse,
    TaskRecurrenceCreate,
    TaskRecurrenceResponse,
    TaskResponse,
    TaskUpdate,
)
from app.schemas.timer import (
    TimerBase,
    TimerCreate,
    TimerListResponse,
    TimerResponse,
    TimerStateAction,
    TimerUpdate,
)
from app.schemas.weather import (
    WeatherCurrentResponse,
    WeatherForecastDay,
    WeatherForecastResponse,
)

__all__ = [
    "ErrorDetail",
    "ErrorResponse",
    "PaginationMeta",
    "SuccessResponse",
    "RegisterRequest",
    "LoginRequest",
    "TokenResponse",
    "UserResponse",
    "UserUpdateRequest",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "TaskRecurrenceCreate",
    "TaskRecurrenceResponse",
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    "ProjectMemberCreate",
    "ProjectMemberResponse",
    "BoardCreate",
    "BoardResponse",
    "BoardColumnCreate",
    "BoardColumnResponse",
    "BoardCardCreate",
    "BoardCardMove",
    "BoardCardResponse",
    "NoteBase",
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "NoteListResponse",
    "IdeaBase",
    "IdeaCreate",
    "IdeaUpdate",
    "IdeaResponse",
    "IdeaListResponse",
    "IdeaPromoteRequest",
    "CalendarEventBase",
    "CalendarEventCreate",
    "CalendarEventUpdate",
    "CalendarEventResponse",
    "CalendarEventListResponse",
    "ReminderBase",
    "ReminderCreate",
    "ReminderUpdate",
    "ReminderSnoozeRequest",
    "ReminderResponse",
    "ReminderListResponse",
    "AlarmBase",
    "AlarmCreate",
    "AlarmUpdate",
    "AlarmToggleRequest",
    "AlarmResponse",
    "AlarmListResponse",
    "TimerBase",
    "TimerCreate",
    "TimerUpdate",
    "TimerStateAction",
    "TimerResponse",
    "TimerListResponse",
    "NotificationBase",
    "NotificationCreate",
    "NotificationResponse",
    "NotificationListResponse",
    "IntegrationConnectRequest",
    "IntegrationResponse",
    "IntegrationStatusResponse",
    "IntegrationListResponse",
    "WeatherCurrentResponse",
    "WeatherForecastDay",
    "WeatherForecastResponse",
]
